Remove joindiaspora.com-specific "performance" hack.
I noticed this because of this Resque job failure that came up:

undefined method `author' for nil:NilClass
/home/diaspora/diaspora/app/models/jobs/notify_local_users.rb:16:in `perform'